name: 'demo_data'

version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'bigquery'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:

  +cluster_id: 0930-015510-ur6hdc0p

  demo_data:

    # configure variables for use in models
    suspected_personas: 5

    +materialized: table

    staging:
      +docs:
        node_color: "CadetBlue"

    marts:
      +docs:
        node_color: "MediumSlateBlue"
    
    metrics:
      +docs:
        node_color: "Maroon"

    challenges:
      py:
        +docs:
          node_color: "Fuchsia"

      sql:
        +docs:
          node_color: "DarkMagenta"

tests:
  +docs:
    node_color: "black"

vars:
  truncate_timespan_to: "{{ dbt_utils.current_timestamp() }}"
  s3_bucket: "s3://dbt-demo-data-2022/jaffle-shop"
